import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import TanstackProvider from "@/providers/TanstackProvider";
  
export const metadata: Metadata = {
  title: "Serenity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <TanstackProvider>
          <SessionProvider>
            <Navbar />
            <Toaster position="top-center" />
            {children}
            <Footer />
          </SessionProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
